### ISSUE TITLE
Failed to load the language-lua-plus package

### ISSUE THREAD

**Issue by mbc1** [Azganoth/language-lua-plus#1]
1. Install  language-lua-plus package
2. run atom 

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [language-lua-plus](https://github.com/Azganoth/language-lua-plus) package 1.2.0

### Stack Trace

Failed to load the language-lua-plus package

```
At Cannot find module '../suggestions/libraries'

Error: Cannot find module '../suggestions/libraries'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-lua-plus/lib/provider.js:5:43)
    at /packages/language-lua-plus/lib/provider.js:12:40)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-lua-plus/lib/main.js:3:30)
    at /packages/language-lua-plus/lib/main.js:24:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
```

### Commands

```
  2x -1:04.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-ctags 5.1.2 
busy-signal 1.4.3 
docblockr 0.13.7 
intentions 1.1.5 
language-lua 0.9.11 
language-lua-plus 1.2.0 
language-terraform 0.8.1 
linter 2.2.0 
linter-jshint 3.1.8 
linter-jslint 11.1.0 
linter-jslinter 0.2.0 
linter-lua 1.0.4 
linter-luacheck 2.0.1 
linter-terraform-syntax 1.2.3 
linter-ui-default 1.7.1 
```

**Comment by Azganoth** [comment]
[Fixed](https://github.com/Azganoth/language-lua-plus/commit/e99893ab2b865a78f57ecdedc70075ed11e279e4) on v1.2.1.
