### ISSUE TITLE
Failed to load a language-lua-plus package grammar

### ISSUE THREAD

**Issue by RuslanLinberg** [Azganoth/language-lua-plus#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [language-lua-plus](https://github.com/Azganoth/language-lua-plus) package 1.7.0

### Stack Trace

Failed to load a language-lua-plus package grammar

```
At The specified module could not be found.
\\?\C:\Users\tgvyh\.atom\packages\language-lua-plus\node_modules\tree-sitter-lua\build\Release\tree_sitter_lua_binding.node in C:\Users\tgvyh\.atom\packages\language-lua-plus\grammars\tree-sitter-lua.json

Error: The specified module could not be found.
\\?\C:\Users\tgvyh\.atom\packages\language-lua-plus\node_modules\tree-sitter-lua\build\Release\tree_sitter_lua_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/language-lua-plus/node_modules/tree-sitter-lua/index.js:2:20)
    at /packages/language-lua-plus/node_modules/tree-sitter-lua/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3235890)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:360047)
    at l.readFile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:359888)
    at u (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:580631)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:581884
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-lua-plus/grammars/tree-sitter-lua.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
language-lua-plus 1.7.0 
```

**Comment by Azganoth** [comment]
It sounds like the dependency module is being deleted, can you disable the antivirus (if you have one) and try to install it again?

**Comment by alfuken** [comment]
I have the same on Mac, what does antivirus have to do with it? :/

**Comment by whitequill** [comment]
`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-lua-plus](https://github.com/Azganoth/language-lua-plus) package 1.7.0


### Stack Trace

Failed to load a language-lua-plus package grammar

```
At The module '\\?\C:\Users\brazg\.atom\packages\language-lua-plus\node_modules\tree-sitter-lua\build\Release\tree_sitter_lua_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in C:\Users\brazg\.atom\packages\language-lua-plus\grammars\tree-sitter-lua.json

Error: The module '\\?\C:\Users\brazg\.atom\packages\language-lua-plus\node_modules\tree-sitter-lua\build\Release\tree_sitter_lua_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/language-lua-plus/node_modules/tree-sitter-lua/index.js:2:20)
    at /packages/language-lua-plus/node_modules/tree-sitter-lua/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3220847)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:360231)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:360072
    at u (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:580740)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:581993
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/language-lua-plus/grammars/tree-sitter-lua.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
file-icons 2.1.41 
ide-cquery 0.14.0 
ide-powershell 0.1.0 
language-65asm 10.4.0 
language-latex 1.2.0 
language-lsl 2.2.0 
language-lua-plus 1.7.0 
language-powershell 5.0.0 
language-webassembly 1.1.1 
language-x86-64-assembly 2.3.0 
latex 0.50.2 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
```

`
I'm also just started to get this. It looks like some node version incompatibility

**Comment by ClemGlacee** [comment]
it's completely broken

**Comment by hugogarrix** [comment]
I've also started getting these errors since yesterday.

**Comment by muzimuzhi** [comment]
@AdmiraalHugo Rebuilding the package works, see https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-incompatible-packages.
